### ISSUE TITLE
Projection des DOM

### ISSUE THREAD

**Issue by TomBor** [antuki/CARTElette#2]
Merci pour cette belle initiative! 

Quelles sont les transformations effectuées sur les .shp des DOM pour les rassembler avec la France métro. ?
Le shapefile en sortie avec la France métro. + les DOM est-il toujours géoréférencé ? Par exemple si j'ajoute des points de villes dans les DOM, est-ce qu'ils vont se placer au bon endroit ?

**Comment by antuki** [comment]
Les transformations effectuées sous R sont les suivantes :
- Chargement des couches brutes de l'IGN sous R (package sf)
- Changement de la projection des couches en projection codée "4326" (c'est-à-dire WGS 84 si je ne me trompe pas)
- Déplacement des DOM grâce à la fonction elide
- Fusion de l'ensemble des couches
- Changement de la projection finale en projection codée "2154" (c'est-à-dire RGF93 / Lambert-93 si je ne me trompe pas)

Le code ayant permis de constituer les couches est mis à disposition dans le dossier associé au COG de la couche. Par exemple pour le COG2017 ici : 
https://github.com/antuki/CARTElette/blob/master/couches_carto/IGN/COG2017/CARTElette_2017_IGN.R
(je ne connais pas ton niveau de connaissance en R mais même sans connaître parfaitement le langage R on arrive parfois à suivre la démarche d'un code).

Les couches carto (.shp) sont stockées à la racine dans https://github.com/antuki/CARTElette/tree/master/couches_carto/IGN/COG2017 par exemple

Pour ta seconde question, pour être totalement transparente, je suis statisticienne de formation. N'ayant jamais eu de cours de géomatique, j'apprends un peu quelques bases sur le tas et je ne suis pas forcément la plus à même de répondre à ta question. PAR CONTRE, je suis très preneuse de ton retour sur cette question (est-ce que le géo-référencement de la nouvelle couche est bon ?) et sur les éventuels problèmes que tu rencontres. 

Merci pour ton retour !

**Comment by TomBor** [comment]
L'idéal serait d'avoir plusieurs projections dans un même fichier et ainsi garder les projections spécifique à chaque DOM. D3 le gère, voir exemple [AlbersUSA](https://bl.ocks.org/mbostock/5629120), en le visualisant mais pas en générant un fichier.

Mais peut-être qu'en changeant la projection de la seconde étape, avant de déplacer les DOM, on pourrait améliorer la forme des DOM en sortie.

En tout cas, je ferais des test en jouant avec ton code.

**Comment by antuki** [comment]
Oui, des packages comme tmap sur R gèrent aussi cela. Les territoires ultra marins ne sont pas "ajoutés" au shapefile mais plutôt à la sortie finale sous forme d'"insets". 

Je pense également qu'il n'est pas impossible d'obtenir le rendu que tu souhaites en modifiant les étapes de changement de projection. A voir. En tous cas je suis bien entendu preneuse de ton retour pour améliorer le rendu des shapefiles proposés.

**Comment by antuki** [comment]
Je ferme l'issue en attendant des pistes de réflexions nouvelles sur les possibilités de projections multiples dans un shapefile, que je n'ai toujours pas à ce jour.
