### ISSUE TITLE
Disposition alternative et échelle

### ISSUE THREAD

**Issue by TomBor** [antuki/CARTElette#3]
Pourquoi ne pas proposer des dispositions alternatives des DOM dans le fichier de sortie ?
Par exemple, aligner les DOM verticalement à gauche ou à droite de la France métro.

Ou mieux pooposer une version à l'échelle ou la surface des DOM seraient comparable entre eux et avec la France métro.

**Comment by antuki** [comment]
Cette proposition est en effet une piste que j'ai en tête pour l'évolution de ce package dans les mois à venir. C'est à dire, proposer une fonction R qui renvoie en sortie une couche carto répondant à différents paramètres de position des DOM et éventuellement de projections. 

Concernant une version à l'échelle, les DOM me paraissent en effet un peu "petits" par rapport à mon imaginaire dans la première proposition de couche que j'ai faite mais je n'ai pourtant pas effectuer de manipulation pour les réduire. Peut-être est-ce la projection utilisée qui n'est pas la plus optimale pour conserver les surfaces (cf. issue #2 pour plus de précisions sur les manipulations effectuées à ce jour) ?

**Comment by antuki** [comment]
La nouvelle version de décembre 2019 prend en compte cette piste d'amélioration. Je ferme donc l'issue.
