### ISSUE TITLE
Usage plus large que R

### ISSUE THREAD

**Issue by TomBor** [antuki/CARTElette#4]
L'usage des fichiers générés dépasse les utilisateurs de R et pourrait servir à un public plus large faisant des cartes.

Serait-il possible de générer et stocker tous les fonds rassemblés dans ce répo ?

Autre suggestion ajouter une [réutilisation sur data.gouv](https://www.data.gouv.fr/fr/datasets/admin-express/)

**Comment by antuki** [comment]
Je ne suis pas sûre d'avoir compris la première question mais si la question est de savoir si les fichiers sont téléchargeables depuis le repo, la question est oui, ils sont stockés par exemple ici : https://github.com/antuki/CARTElette/tree/master/couches_carto/IGN/COG2017

Pour la question de réutilisation sur data.gouv, je comptais attendre quelques temps, voir les premiers retours et avoir une vision un peu plus claire de l'architecture globale finale du projet avant de poster quelque chose de plus construit.

**Comment by TomBor** [comment]
Merci, oui c'était bien ma question, je n'avais pas suffisamment regardé le repo.
