### ISSUE TITLE
Prochaine MAJ ?

### ISSUE THREAD

**Issue by camilomorenokuratomi** [antuki/CARTElette#5]
Le package est vraiment génial ! 

Est-ce qu'il y aura une mise à jour pour 2018 ?

Merci encore.

**Comment by antuki** [comment]
Il suffisait de demander ;) Merci pour l'intérêt que vous portez à ce package, cela fait plaisir à lire !

**Comment by camilomorenokuratomi** [comment]
Merci beaucoup pour la MAJ! 

:)
